module.exports = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'documentation'
    }
  ],
  contributeSidebar: [
    {
      type: 'autogenerated',
      dirName: 'contribute'
    }  
  ]
};
