module.exports = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Mapping Tools',
      items: [
        {
          type: 'autogenerated',
          dirName: '01-mapping-tools', // Generate sidebar slice from docs/01-mapping-tools
        },
      ],
    },
    {
      type: 'category',
      label: 'General',
      items: [
        {
          type: 'autogenerated',
          dirName: '02-general', // Generate sidebar slice from docs/02-general
        },
      ],
    },
    {
      type: 'category',
      label: 'Tools',
      items: [
        {
          type: 'autogenerated',
          dirName: '03-tools', // Generate sidebar slice from docs/03-tools
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: '04-guides', // Generate sidebar slice from docs/04-guides
        },
      ],
    },
  ]
};
